---
name: Check (Ruff)

on:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - "**/README*"
      - ".github/workflows/check_types.yml"
      - ".github/workflows/test.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync

      - name: Build the project with uv
        run: uv tool install .

      - name: Run the built project to check it works
        run: my-cool-app --help
