---
name: Type Check (Mypy, ty)

on:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - "**/README*"

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --extra type --extra test

      - name: Check types with mypy
        run: .venv/bin/mypy

  ty:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --extra type --extra test

      - name: Check types with mypy
        run: .venv/bin/ty check .
