---
name: Lint (Ruff)

on:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - '**/README.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cookiecutter
        run: pip install cookiecutter

      - name: Generate cookiecutter project
        run: cookiecutter python-boilerplate --no-input
        working-directory: ../

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        working-directory: ../my-cool-app
        run: uv sync --no-group test --no-group type --no-group dev

      - name: Lint with ruff
        working-directory: ../my-cool-app
        run: uv run ruff check .
