---
name: Check (Ruff)

on:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - "**/README*"
      - ".github/workflows/check_types.yml"
      - ".github/workflows/test.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
